PiDev-web/src/main/java/Bean/CatalogBean.java
package Bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import Entities.Catalog;
import Entities.Formation;
import Services.CatalogService;
import Services.FormationService;

@ManagedBean(name= "CatalogBean", eager = true)
@SessionScoped
public class CatalogBean implements Serializable{

private static final long serialVersionUID = 1L;
	

	private int id_cat;
	private String nom_cat;
	private List<Formation> listformations = new ArrayList<Formation>();
	private List<Catalog> Catalogs;
	private static  List<Formation> selectedFormations;
	private static List<Formation> formations;
	private int idselected ;
	
	@EJB
	CatalogService cs;
	@EJB
	FormationService fs;
	
	public  List<Formation> Affiche() {
		 formations = new ArrayList<Formation>();
		formations=  fs.findAllFormations();
		return formations;
	}
	public void AddCatalog() {
		 Catalog c = new Catalog(nom_cat);
		 List<Formation> selectedFormations = new ArrayList<Formation>();
		 c.setListformations(selectedFormations);
		cs.ajouterCatalog(c)	; 
		
		
	
	}
	public void affecterdesformations(int ids) {
	
		cs.affecterFormationAcatalog(ids, id_cat);
	
	}
	public List<Catalog> afficherCatalogs() {
		Catalogs= new ArrayList<Catalog>();
		Catalogs= cs.findAllCatalog();
		return Catalogs;
	}
	public void removeCatalog(int catalogId) {
		cs.removeCatalog(catalogId);

	}
	public String detailsCatalog(int id_cat) {

		return "datailsCat";}
	public List<Formation> getListformations(int id_cat) {
		 detailsCatalog(id_cat);
		listformations = new ArrayList<Formation>();
		cs.getListFormationByCatId(id_cat);
		return listformations;
	}

	public void setListformations(List<Formation> listformations) {
		this.listformations = listformations;
	}

	public List<Catalog> getCatalogs() {
		return Catalogs;
	}

	public void setCatalogs(List<Catalog> catalogs) {
		Catalogs = catalogs;
	}

	public int getId_cat() {
		return id_cat;
	}

	public void setId_cat(int id_cat) {
		this.id_cat = id_cat;
	}

	public String getNom_cat() {
		return nom_cat;
	}

	public void setNom_cat(String nom_cat) {
		this.nom_cat = nom_cat;
	}

	public List<Formation> getlistformations() {
		
		return listformations;
	}

	public void setFormations(List<Formation> listformations) {
		this.listformations = listformations;
	}
	public  List<Formation> getSelectedFormations() {
		return selectedFormations;
	}
	public  void setSelectedFormations(List<Formation> selectedFormations) {
		CatalogBean.selectedFormations=selectedFormations;
	}
	public int getIdselected() {
		return idselected;
	}
	public void setIdselected(int idselected) {
		this.idselected = idselected;
	}
	public CatalogService getCs() {
		return cs;
	}
	public void setCs(CatalogService cs) {
		this.cs = cs;
	}
	public FormationService getFs() {
		return fs;
	}
	public void setFs(FormationService fs) {
		this.fs = fs;
	}
	public List<Formation> getFormations() {
		return formations;
	}
	public String listSelectedFormation(List<Formation> listformations){
		selectedFormations= listformations;
		return "listFormationByCatId?faces-redirect=true&includeViewParams=true";
	}
	
}

PiDev-web/src/main/java/Bean/FicheBean.java
package Bean;

import java.io.Serializable;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import Entities.Employe;
import Entities.FicheCompetence;
import Enumerates.MaitriseCompetence;
import Services.CompetenceService;

@ManagedBean(name= "FicheBean", eager = true)
@SessionScoped
public class FicheBean implements Serializable {
	
		private static final long serialVersionUID = 1L;
		private Employe user;

		private int NoteConception;
		private int NoteGestionProjet;
	    private int NoteReporting;
		private int NoteDevLogiciel;
		private int NoteMethodesAgile;
		private MaitriseCompetence maitrise;
		@EJB
		CompetenceService cos;
		public void Ajoutfiche() {
			FicheCompetence f =new FicheCompetence(NoteConception, NoteGestionProjet, NoteReporting, NoteDevLogiciel, NoteMethodesAgile, maitrise);
			cos.ajouterFiche(f);
		}
		

		public MaitriseCompetence getMaitrise() {
			return maitrise;
		}



		public void setMaitrise(MaitriseCompetence maitrise) {
			this.maitrise = maitrise;
		}


		public Employe getUser() {
			return user;
		}
		public void setUser(Employe user) {
			this.user = user;
		}
		public int getNoteConception() {
			return NoteConception;
		}
		public void setNoteConception(int noteConception) {
			NoteConception = noteConception;
		}
		public int getNoteGestionProjet() {
			return NoteGestionProjet;
		}
		public void setNoteGestionProjet(int noteGestionProjet) {
			NoteGestionProjet = noteGestionProjet;
		}
		public int getNoteReporting() {
			return NoteReporting;
		}
		public void setNoteReporting(int noteReporting) {
			NoteReporting = noteReporting;
		}
		public int getNoteDevLogiciel() {
			return NoteDevLogiciel;
		}
		public void setNoteDevLogiciel(int noteDevLogiciel) {
			NoteDevLogiciel = noteDevLogiciel;
		}
		public int getNoteMethodesAgile() {
			return NoteMethodesAgile;
		}
		public void setNoteMethodesAgile(int noteMethodesAgile) {
			NoteMethodesAgile = noteMethodesAgile;
		}

		
		public CompetenceService getCos() {
			return cos;
		}
		public void setCos(CompetenceService cos) {
			this.cos = cos;
		}
		public static long getSerialversionuid() {
			return serialVersionUID;
		}
		
		
}

PiDev-web/src/main/java/Bean/FormationBean.java
package Bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import Entities.Catalog;
import Entities.FicheCompetence;
import Entities.Formation;
import Enumerates.MaitriseCompetence;
import Services.CatalogService;
import Services.CompetenceService;
import Services.FormationService;

@ManagedBean(name= "FormationBean", eager = true)
@SessionScoped
public class FormationBean implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int id_for;

	private String nom_for;
	private String prerequis;
    private MaitriseCompetence niveauobt;
	private String nom_anim;
	private String description;
	private Date date_debut;
	private int duree;
	private String lieu;
	private int formationIdToBeUpdated;
	private List<Formation> formations;
	private Formation formation ;
	private static Catalog selectedCatalog;
	private int selectedCatalogId;
	private List<Catalog> Catalogs;

	
	@EJB
	FormationService fs;
	@EJB
	CatalogService cs;
	@EJB
	CompetenceService cos;
	/*public List<Catalog> afficheCat(){
		Catalogs= cs.findAllCatalog();
		return Catalogs;
	}*/
	
	public String ajouterFormation() {
		 Formation f =new Formation(nom_for, prerequis, niveauobt, nom_anim, description, date_debut, duree, lieu);
		 Catalog SelectedCatalog=new Catalog();
			System.out.println("2");
			SelectedCatalog.setId_cat(selectedCatalogId);
			System.out.println(selectedCatalogId);
			
			
			if (cs.nombreformationInCatalog(SelectedCatalog)>5){
				System.out.println("ça marche pas");	
				System.out.println(cs.nombreformationInCatalog(SelectedCatalog));	

				FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,
						"vous ne pouvez plus ajouter de formation", ""));
		}else{
			
			
			
			
			f.setCat(SelectedCatalog);
			fs.ajouterFormation(f);}
		return "Affiche";
	}
	public String  displayFormation(Formation form) {
		this.setFormationIdToBeUpdated(form.getId_for());
		this.setNom_for(form.getNom_for());
		this.setPrerequis(form.getPrerequis());
		this.setNiveauobt(form.getNiveauobt());
		this.setNom_anim(form.getNom_anim());
		this.setDescription(form.getDescription());
		this.setDate_debut(form.getDate_debut());
		this.setDuree(form.getDuree());
		this.setLieu(form.getLieu());
		return "Ajout";
		

	}
	public String modifierformation() {
		Formation f = new Formation();
		f.setId_for(this.getFormationIdToBeUpdated());
		f.setNom_for(this.getNom_for());
		f.setPrerequis(this.getPrerequis());
		f.setNiveauobt(this.getNiveauobt());
		f.setNom_anim(this.getNom_anim());
		f.setDescription(this.getDescription());
		f.setDate_debut(this.getDate_debut());
		f.setDuree(this.getDuree());
		f.setLieu(this.getLieu());
		fs.updateFormation(f);
		return "Affiche";
	}
	
	public List<Formation> afficherFormations() {
		formations= new ArrayList<Formation>();

		formations= fs.findAllFormations();
		return formations;
	}
	public void removeFormation(int formId) {
		fs.removeFormation(formId);

	}
	public Formation getFormationbyid(int forid) {
		return fs.getFormationById(forid);
	}
	public void affecterFormationAcatalog(int formationId, int catId) {
		
		fs.affecterFormationAcatalog(formationId, catId);
	}
	
	public void participer(Formation form,int id ) {
		id=1;
		FicheCompetence f = cos.getFicheByIdUser(id);
		int score_user =( f.getNoteConception()+f.getNoteDevLogiciel()+f.getNoteGestionProjet()
		+f.getNoteMethodesAgile()+f.getNoteReporting())/5;
		
		if(score_user>15 && f.getMaitrise().equals(form.getNiveauobt() )) {
		
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,
			"Passer le niveau suivant ", ""));
			
		}
		else if(score_user>15 && form.getNiveauobt().equals("junior") &&( f.getMaitrise().equals("senior")|| f.getMaitrise().equals("specialiste")||f.getMaitrise().equals("expert")) ) {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,
					"Ce niveau est inferieur à votre niveau de competence ", ""));
		}
		
	}
	public int getId_for() {
		return id_for;
	}
	public void setId_for(int id_for) {
		this.id_for = id_for;
	}
	public String getNom_for() {
		return nom_for;
	}
	public void setNom_for(String nom_for) {
		this.nom_for = nom_for;
	}
	public String getPrerequis() {
		return prerequis;
	}
	public void setPrerequis(String prerequis) {
		this.prerequis = prerequis;
	}
	
	public MaitriseCompetence getNiveauobt() {
		return niveauobt;
	}
	public void setNiveauobt(MaitriseCompetence niveauobt) {
		this.niveauobt = niveauobt;
	}

	
	public String getNom_anim() {
		return nom_anim;
	}
	public void setNom_anim(String nom_anim) {
		this.nom_anim = nom_anim;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Date getDate_debut() {
		return date_debut;
	}
	public void setDate_debut(Date date_debut) {
		this.date_debut = date_debut;
	}
	public int getDuree() {
		return duree;
	}
	public void setDuree(int duree) {
		this.duree = duree;
	}
	public String getLieu() {
		return lieu;
	}
	public void setLieu(String lieu) {
		this.lieu = lieu;
	}
	public Formation getFormation() {
		return formation;
	}

	public void setFormation(Formation formation) {
		this.formation = formation;
	}

	public List<Formation> getFormations() {
	formations= fs.findAllFormations();

		return formations;
	}
	
	public void setFormations(List<Formation> formations) {
		this.formations = formations;
	}
	public int getFormationIdToBeUpdated() {
		return formationIdToBeUpdated;
	}
	public void setFormationIdToBeUpdated(int formationIdToBeUpdated) {
		this.formationIdToBeUpdated = formationIdToBeUpdated;
	}
	
	public FormationService getFs() {
		return fs;
	}
	public void setFs(FormationService fs) {
		this.fs = fs;
	}
	public Catalog getSelectedCatalog() {
		return selectedCatalog;
	}
	public void setSelectedCatalog(Catalog selectedCatalog) {
		FormationBean.selectedCatalog = selectedCatalog;
	}
	public int getSelectedCatalogId() {
		return selectedCatalogId;
	}
	public void setSelectedCatalogId(int selectedCatalogId) {
		this.selectedCatalogId = selectedCatalogId;
	}

	public List<Catalog> getCatalogs() {
		Catalogs=cs.findAllCatalog();
		return Catalogs;
	}

	public void setCatalogs(List<Catalog> catalogs) {
		Catalogs = catalogs;
	}
	public void participate(int id_for,int id_user) {}
	
}

PiDev-web/src/main/java/Bean/MaitriseBean.java
package Bean;

import java.io.Serializable;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;

import Enumerates.MaitriseCompetence;

@ManagedBean(name= "MaitriseBean")
@ApplicationScoped
public class MaitriseBean implements Serializable {
	private static final long serialVersionUID= 1L;
	public MaitriseCompetence[] getMaitrises() {
		return MaitriseCompetence.values();
	}
	
}

PiDev-web/src/main/webapp/Pages/admin/formation/Affiche.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
xmlns:f="http://java.sun.com/jsf/core" 
xmlns:h="http://java.sun.com/jsf/html" 
xmlns:ui="http://java.sun.com/jsf/facelets"
template="/tmp/layoutadmin1.xhtml"
xmlns:p="http://primefaces.org/ui">


 <ui:define name="menu">
<h:form id="content">
 <h:panelGroup columns="2">

<h:dataTable id="example" value="#{FormationBean.formations}" var="formation" 
 class="table table-sm table-striped table-hoverd"  style="width:100%"
   paginator="true" 
           >

<h:column><f:facet name="header"><h:outputText value="nom formation" /></f:facet>
<h:outputText value="#{formation.nom_for}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="prerequis" /></f:facet>
<h:outputText value="#{formation.prerequis}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="niveau atteind" /></f:facet>
<h:outputText value="#{formation.niveauobt}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="nom formatteur" /></f:facet>
<h:outputText value="#{formation.nom_anim}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="Description" /></f:facet>
<h:outputText value="#{formation.description}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="Date" /></f:facet>
<h:outputText value="#{formation.date_debut}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="Duree" /></f:facet>
<h:outputText value="#{formation.duree}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="Lieu" /></f:facet>
<h:outputText value="#{formation.lieu}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="Catalog" /></f:facet>
<h:outputText value="#{formation.cat.nom_cat}" /></h:column>
<h:column>
<f:facet name="header"><h:outputText value="Action" /></f:facet>
<h:commandButton class="btn-info" action="#{FormationBean.removeFormation(formation.id_for)}" value="Supprimer" />
</h:column>
<h:column>
<f:facet name="header"><h:outputText value="Action" /></f:facet>
<h:commandButton class="btn-info" action="#{FormationBean.displayFormation(formation) }" value="voir" />
</h:column>
<h:column>
<f:facet name="header"><h:outputText value="Action" /></f:facet>
<h:commandButton class="btn-info" action="#{FormationBean.participer(formation) }" value="participer" />
</h:column>
</h:dataTable>
</h:panelGroup>
</h:form>
<script>
$(document).ready(function() {
    $('#example').DataTable();
} );
</script>
</ui:define>
</ui:composition>
 

PiDev-web/src/main/webapp/Pages/admin/formation/Ajout.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
xmlns:f="http://java.sun.com/jsf/core" 
xmlns:h="http://java.sun.com/jsf/html" 
xmlns:ui="http://java.sun.com/jsf/facelets"
template="/tmp/layoutadmin1.xhtml"
xmlns:p ="http://primefaces.org/ui">






 
<style type="text/css">
    .value {
        font-weight: bold;
    }
</style>
 


<ui:define name="menu">
<h:form id="content" >
<h1>Ajout formation</h1>
<h:panelGrid columns="2" >

<h:outputText value="Nom de la formation" /> <h:inputText value="#{FormationBean.nom_for}" class="form-control " required="true" requiredMessage="champs obligatoire" > 


</h:inputText> 

<h:outputText value="Prerequis" /> <h:inputText value="#{FormationBean.prerequis}" class="form-control" 
required="true" requiredMessage="champs obligatoire"/>
<h:outputText value="Niveau à atteindre"></h:outputText>
<h:selectOneMenu id="m" value="#{FormationBean.niveauobt}" class="btn btn-secondary dropdown-toggle form-control" >
<f:selectItem itemLabel="select maitrise" itemValue="" converter="javax.faces.Enum"/>

		<f:selectItems value="#{MaitriseBean.maitrises}"  />
			</h:selectOneMenu>



<h:outputText value="Nom du formateur" /> <h:inputText value="#{FormationBean.nom_anim}" class="form-control" required="true" requiredMessage="champs obligatoire"/>
<h:outputText value="Description" /> <h:inputTextarea cols="14" rows="4" style="width:150" value="#{FormationBean.description}" class="form-control" required="true" requiredMessage="champs obligatoire" > </h:inputTextarea>
<h:outputText value="Date debut" /> 
 <h:inputText value="#{FormationBean.date_debut}" class="form-control " required="true" requiredMessage="MM/dd/yyyy"> 
    <f:convertDateTime pattern="MM/dd/yyyy" />
</h:inputText>

<h:outputText value="Durée" /> <h:inputText value="#{FormationBean.duree}" class="form-control" required="true" requiredMessage="champs obligatoire"/>
<h:outputText value="Lieu" /> <h:inputText value="#{FormationBean.lieu}" class="form-control" required="true" requiredMessage="champs obligatoire"/>
<h:outputText value="Selectionner un catalog"></h:outputText>

<h:selectOneMenu id="k" value="#{FormationBean.selectedCatalogId}" class="form-control" >

		<f:selectItems value="#{FormationBean.catalogs}" var="category"
		 itemValue="#{category.id_cat}" itemLabel="#{category.nom_cat}" converter="javax.faces.Integer" />
			</h:selectOneMenu>

<h:commandButton id="btn" class="btn btn-info btn-block" value="ok"  action="#{FormationBean.ajouterFormation()}" />
<h:message for="btn"/>
<h:commandButton id="btn1" class="btn btn-info btn-block" value="update" action="#{FormationBean.modifierformation()}" />
<h:message for="btn"/>
</h:panelGrid>
</h:form>


</ui:define>
</ui:composition>

PiDev-web/src/main/webapp/Pages/admin/formation/Catalog.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
xmlns:f="http://java.sun.com/jsf/core" 
xmlns:h="http://java.sun.com/jsf/html" 
xmlns:ui="http://java.sun.com/jsf/facelets"
template="/tmp/layoutadmin1.xhtml"
xmlns:p="http://primefaces.org/ui">


<ui:define name="menu">
<h:form id="content">
<h1>Catalog</h1>
<h:panelGrid columns="2">
<p> Créer un nouveau catalog<br />

</p>
<h:outputText value="Nom du catalog" /> <h:inputText value="#{CatalogBean.nom_cat}" class="form-control" />

<h:commandButton id="btn" class="btn btn-info btn-block" value="Suivant>>" action="#{CatalogBean.AddCatalog()}" />
<h:message for="btn"/>

 <h:panelGroup columns="2">


</h:panelGroup>
<h:dataTable value="#{CatalogBean.afficherCatalogs()}" var="Catalog"  class="table table-sm table-striped table-hoverd"  style="width:100%">

<h:column><f:facet name="header"><h:outputText value=" Catalog" /></f:facet>
<h:outputText value="#{Catalog.nom_cat}" /></h:column>

<h:column>
<f:facet name="header"><h:outputText value="Action" /></f:facet>
<h:commandButton class="btn-info" action="#{CatalogBean.removeCatalog(Catalog.id_cat)}" value="Supprimer" />
</h:column>
<h:column>
<f:facet name="header"><h:outputText value="Action" /></f:facet>
<h:commandButton class="btn-info" action="#{CatalogBean.detailsCatalog(Catalog.id_cat)}" value="Details" />
</h:column>
</h:dataTable>
</h:panelGrid>
</h:form>

</ui:define>
</ui:composition>

PiDev-web/src/main/webapp/Pages/admin/formation/Fiche.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
xmlns:f="http://java.sun.com/jsf/core" 
xmlns:h="http://java.sun.com/jsf/html" 
xmlns:ui="http://java.sun.com/jsf/facelets"
template="/tmp/layout.xhtml"
xmlns:p="http://primefaces.org/ui"
>

<ui:define name="menu">
<h:form id="content">
<h1>Ajout formation</h1>
<h:panelGrid columns="2">
<h:outputText value="NoteConception" /> <h:inputText value="#{FicheBean.noteConception}" />
<h:outputText value="NoteGestionProjet" /> <h:inputText value="#{FicheBean.noteGestionProjet}" />
<h:outputText value="NoteReporting" /> <h:inputText value="#{FicheBean.noteReporting}" />
<h:outputText value="NoteDevLogiciel" /> <h:inputText value="#{FicheBean.noteDevLogiciel}" />

<h:outputText value="NoteMethodesAgile" /> <h:inputText value="#{FicheBean.noteMethodesAgile}" />


<h:selectOneMenu value="#{FicheBean.maitrise}">
<f:selectItem itemLabel="Choisir Role" itemValue=""/>
		<f:selectItems value="#{MaitriseBean.maitrises}" />
			</h:selectOneMenu>

<h:commandButton id="btn" value="ok" action="#{FicheBean.Ajoutfiche()}" />
<h:message for="btn"/>
<h:commandButton id="btn1" value="update" action="#{FormationBean.modifierformation()}" />
<h:message for="btn"/>
</h:panelGrid>
</h:form>
</ui:define>
</ui:composition>

PiDev-web/src/main/webapp/Pages/admin/formation/datailsCat.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
xmlns:f="http://java.sun.com/jsf/core" 
xmlns:h="http://java.sun.com/jsf/html" 
xmlns:ui="http://java.sun.com/jsf/facelets"
template="/tmp/layoutadmin1.xhtml"
xmlns:p="http://primefaces.org/ui">


 <ui:define name="menu">
<h:form id="content">
 <h:panelGroup columns="2">
<h1>Details du Catalog</h1>

<h:dataTable value="#{CatalogBean.listformations}" var="formation"  class="table table-sm table-striped table-hoverd"  style="width:100%"
   paginator="true" >

<h:column><f:facet name="header"><h:outputText value="nom formation" /></f:facet>
<h:outputText value="#{formation.nom_for}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="prerequis" /></f:facet>
<h:outputText value="#{formation.prerequis}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="niveau atteind" /></f:facet>
<h:outputText value="#{formation.niveauobt}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="nom formatteur" /></f:facet>
<h:outputText value="#{formation.nom_anim}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="Description" /></f:facet>
<h:outputText value="#{formation.description}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="Date" /></f:facet>
<h:outputText value="#{formation.date_debut}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="Duree" /></f:facet>
<h:outputText value="#{formation.duree}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="Lieu" /></f:facet>
<h:outputText value="#{formation.lieu}" /></h:column>

<h:column>
<f:facet name="header"><h:outputText value="Action" /></f:facet>
<h:commandButton action="#{CatalogBean.removeFormationFromCat(formation.id_for)}" value="Supprimer" />
</h:column>
<h:column>
<f:facet name="header"><h:outputText value="Action" /></f:facet>
<h:commandButton action="#{FormationBean.displayFormation(formation) }" value="voir" />
</h:column>
</h:dataTable>
</h:panelGroup>
</h:form>

</ui:define>
</ui:composition>
 

PiDev-web/src/main/webapp/Pages/admin/formation/scroll.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
xmlns:f="http://java.sun.com/jsf/core" 
xmlns:h="http://java.sun.com/jsf/html" 
xmlns:ui="http://java.sun.com/jsf/facelets"
template="/tmp/layoutadmin1.xhtml"
xmlns:p="http://primefaces.org/ui">


 <ui:define name="menu">
<h:form id="content">
 <h:panelGroup columns="2">

<h:dataTable value="#{FormationBean.formations}" var="formation"  class="table table-sm table-striped table-hoverd"  style="width:100%">

<h:column><f:facet name="header"><h:outputText value="nom formation" /></f:facet>
<h:outputText value="#{formation.nom_for}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="prerequis" /></f:facet>
<h:outputText value="#{formation.prerequis}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="niveau atteind" /></f:facet>
<h:outputText value="#{formation.niveauobt}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="nom formatteur" /></f:facet>
<h:outputText value="#{formation.nom_anim}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="Description" /></f:facet>
<h:outputText value="#{formation.description}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="Date" /></f:facet>
<h:outputText value="#{formation.date_debut}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="Duree" /></f:facet>
<h:outputText value="#{formation.duree}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="Lieu" /></f:facet>
<h:outputText value="#{formation.lieu}" /></h:column>

<h:column><f:facet name="header"><h:outputText value="Catalog" /></f:facet>
<h:outputText value="#{formation.cat.nom_cat}" /></h:column>
<h:column>
<f:facet name="header"><h:outputText value="Action" /></f:facet>
<h:commandButton action="#{FormationBean.removeFormation(formation.id_for)}" value="Supprimer" />
</h:column>
<h:column>
<f:facet name="header"><h:outputText value="Action" /></f:facet>
<h:commandButton action="#{FormationBean.displayFormation(formation) }" value="voir" />
</h:column>
<h:column>
<f:facet name="header"><h:outputText value="Action" /></f:facet>
<h:commandButton action="#{FormationBean.displayFormation(formation) }" value="participer" />
</h:column>
</h:dataTable>
</h:panelGroup>
</h:form>

</ui:define>
</ui:composition>
 