PiDev-web/src/main/java/resources/MissionBean.java
package resources;

import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;
import java.io.FileNotFoundException;
import java.io.IOException;
import Entities.*;
import Services.*;


@Path("mission")
@RequestScoped
public class MissionBean  {
	
	@Inject
	MissionService ms = new MissionService();

	@GET
	@Produces(MediaType.APPLICATION_JSON)
	@Path("serch/{subject}")
	public Response recherche(@PathParam("subject") String subject)throws Exception  
	   
	
	{
		List<Mission> list=ms.displayMissions(); 
		 List<Mission> list1=ms.displayMissionsubject(subject); 
		 List<Mission> list2=ms.displayMissiondescrip(subject); 
			List<Mission> list3=ms.displayMissionplace(subject); 

		
		 if( list2.isEmpty()&&list1.isEmpty()) {
			 
    		
    		return Response.status(Status.ACCEPTED).entity("liste par place \n "+list3).build();
		
			
		}
		 else if(  list2.isEmpty()&&list3.isEmpty()) {
	    		
	    		return Response.status(Status.ACCEPTED).entity("liste par sujet \n "+list1).build();
			
				
			}
		 else if(  list3.isEmpty()&&list1.isEmpty()) {
	    		
	    		return Response.status(Status.ACCEPTED).entity("liste par description \n "+list2).build();
			
				
			}

			return Response.status(Status.ACCEPTED).entity("all \n "+list).build();


	}
	
	
	
	@GET
	@Produces(MediaType.APPLICATION_JSON)
	@Path("{refrence}")
	public Response ShowReclamationDetails(@PathParam("refrence")int refrence)
	
	{
			
	
		boolean exist=ms.getref(refrence);
	
		
		System.out.println("******************************************"+exist);
		
	if (exist == false )
		{
			return Response.status(Status.BAD_REQUEST).entity("Veuillez choisir un refrence différent ").build();
	
		
		}
		
		
	return Response.ok(ms.ShowClaimDetails(refrence)).build();
	}
	
	
    @GET
	@Produces(MediaType.APPLICATION_JSON)
	public Response getMissions() {
		return Response.ok(ms.displayMissions()).build();
	}
    
    @Secured
	@POST 
	@Consumes(MediaType.APPLICATION_JSON)
	@Produces(MediaType.APPLICATION_JSON)
	public Response addmission(Mission emp)
	{
		 if (emp.getSubject()==null) {
			return Response.status(Status.BAD_REQUEST).entity("Veuillez entre un Subject ").build();
			
		}
		 else if (emp.getDescription()==null) {
			return Response.status(Status.BAD_REQUEST).entity("Veuillez entre un description ").build();
			
		}
		else if (emp.getEstimation()==null) {
			return Response.status(Status.BAD_REQUEST).entity("Veuillez entre un Estimation ").build();
			
		}
	
		else if (emp.getSkillsRequired()==null) {
			return Response.status(Status.BAD_REQUEST).entity("Veuillez entre un Skill ").build();
			
		}
		ms.createMission(emp);
	
		
			return Response.status(Status.CREATED).entity("Registration Successful").build();
		
		
	}
	@Secured 
	@DELETE
	@Produces(MediaType.APPLICATION_JSON)
	@Path("{refrence}")
	public Response DeleteReclamation(@PathParam("refrence")int refrence)
	{
	boolean exist=ms.getref(refrence);
if (exist == false)
	{
		return Response.status(Status.BAD_REQUEST).entity("Veuillez choisir un refrence différent ").build();
	}
	
      ms.removeMission(refrence);

	return Response.status(Status.ACCEPTED).entity("deleted").build();
	}

	@Secured 
	@PUT 
	@Path("{refrence}")
	@Consumes(MediaType.APPLICATION_JSON)
	@Produces(MediaType.APPLICATION_JSON)
	public Response updateReclamationAdmin(@PathParam("refrence")int refrence ,Mission emp)  {
		boolean exist=ms.getref(refrence);
		if (exist == false)
			{
				return Response.status(Status.BAD_REQUEST).entity("Veuillez choisir un refrence différent ").build();
			}
		else if (emp.getSubject()==null) {
				return Response.status(Status.BAD_REQUEST).entity("Veuillez entre un Subject ").build();
				
			}
			 else if (emp.getDescription()==null) {
				return Response.status(Status.BAD_REQUEST).entity("Veuillez entre un description ").build();
				
			}
			else if (emp.getEstimation()==null) {
				return Response.status(Status.BAD_REQUEST).entity("Veuillez entre un Estimation ").build();
				
			}
		
			else if (emp.getSkillsRequired()==null) {
				return Response.status(Status.BAD_REQUEST).entity("Veuillez entre un Skill ").build();
				
			}
		ms.updateMissionl(emp, refrence);
		return Response.status(Status.ACCEPTED).entity("updated:\n :").build();

	}
/*
	@GET
	@Produces(MediaType.APPLICATION_JSON)
    @Path("code/{code}")
	public Response search (@PathParam(value="code") int n)
	{
		
		System.out.println(getMods().size());
		for (Module va : mods) {
			System.out.println("11111");
			if (va.getCoefficient()==n) {
				System.out.println(va.toString());
				return Response.status(Status.CREATED).entity(va).build();
				
				
			}
 
		}
		return Response.status(Status.BAD_REQUEST).build();

	}*/
}

PiDev-web/src/main/webapp/Pages/admin/Done.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"
>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="/tmp/layoutadmin1.xhtml">

	<ui:define name="content">
    	     <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>you put two same skills</h2>
                </div>
                <div class="col-lg-2">

                </div>
            </div>
   	</ui:define>
</ui:composition>

PiDev-web/src/main/webapp/Pages/admin/NotDonne.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"
>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="/tmp/layoutadmin1.xhtml">
	
	
	
	<ui:define name="content">
    	     <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>sorry somthing is wrong</h2>
                </div>
                <div class="col-lg-2">

                </div>
            </div>
   	</ui:define>
</ui:composition>

PiDev-web/src/main/webapp/Pages/admin/PrivateClients.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"	
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/tmp/template.xhtml">

	<ui:define name="title">All clients</ui:define>
	<ui:define name="content">
	
	
<h:dataTable value="#{ClientBean.privateClients}" var="client" border="1">
		<h:column>
			<f:facet name="header">
			<h:outputText value="cid" />
			</f:facet>
			<h:outputText value="#{client.userId}" />
		</h:column>
		<h:column>
			<f:facet name="header">
			<h:outputText value="Last name" />
			</f:facet>
			<h:outputText value="#{client.nom}" />
		</h:column>
		<h:column>
			<f:facet name="header">
			<h:outputText value="Name" />
			</f:facet>
			<h:outputText value="#{client.prenom}" />
		</h:column>
		<h:column>
			<f:facet name="header">
			<h:outputText value="Type" />
			</f:facet>
			<h:outputText value="#{client.clientType}" />
		</h:column>
		<h:column>
			<f:facet name="header">
				<h:outputText value="Handle" />
			</f:facet>
			<h:commandButton value="Consult" action="#{Method(client)}"/>
			<h:commandButton value="Modify" action="#{Method(client)}"/>
			<h:commandButton value="Delete" action="#{Method(client)}"/>
		</h:column>
	
		</h:dataTable>
		
		</ui:define>
	
	
	
</ui:composition>

PiDev-web/src/main/webapp/Pages/admin/PublicClients.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"	
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/tmp/template.xhtml">

	<ui:define name="title">All clients</ui:define>
	<ui:define name="content">
	
	
<h:dataTable value="#{ClientBean.publicClients}" var="client" border="1">
		<h:column>
			<f:facet name="header">
			<h:outputText value="cid" />
			</f:facet>
			<h:outputText value="#{client.userId}" />
		</h:column>
		<h:column>
			<f:facet name="header">
			<h:outputText value="Last name" />
			</f:facet>
			<h:outputText value="#{client.nom}" />
		</h:column>
		<h:column>
			<f:facet name="header">
			<h:outputText value="Name" />
			</f:facet>
			<h:outputText value="#{client.prenom}" />
		</h:column>
		<h:column>
			<f:facet name="header">
			<h:outputText value="Type" />
			</f:facet>
			<h:outputText value="#{client.clientType}" />
		</h:column>
		<h:column>
			<f:facet name="header">
				<h:outputText value="Handle" />
			</f:facet>
			<h:commandButton value="Consult" action="#{Method(client)}"/>
			<h:commandButton value="Modify" action="#{Method(client)}"/>
			<h:commandButton value="Delete" action="#{Method(client)}"/>
		</h:column>
	
		</h:dataTable>
		
		</ui:define>
	
	
	
</ui:composition>

PiDev-web/src/main/webapp/Pages/admin/RManagement.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/tmp/template.xhtml">

	<ui:define name="title">Resources information</ui:define>
	<ui:define name="content">
	
	<h:panelGrid columns="2">
	<h:outputText value="Number of all resources"/>
    <h:outputText value="#{resourceMBean.nbrresources" />	
	</h:panelGrid>
	
	<h:panelGrid columns="3">
	<h:outputText value="Number of all employees"/>
    <h:outputText value="#{resourceMBean.nbremployee}" />
    <h:outputText value="#{resourceMBean.pourcentageemploye}" />	
	</h:panelGrid>
	
	<h:panelGrid columns="3">
	<h:outputText value="Number of all freelancers"/>
    <h:outputText value="#{resourceMBean.nbrfreelancers" />	
    <h:outputText value="#{resourceMBean.pourcentagefreelancer}" />
	</h:panelGrid>

	</ui:define>	
</ui:composition>

PiDev-web/src/main/webapp/Pages/admin/addMission.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" template="/tmp/layoutadmin1.xhtml"
	xmlns:a="http://xmlns.jcp.org/jsf/passthrough">

	<ui:define name="content">
		<ui:param name="page_name" value="Connexion" /> 
			    					> 
			<h:form id="form">

			<h:panelGroup columns="2">
				<h:form>
					<table>
						<tr>
							<td><h:outputText value="subject"></h:outputText></td>
							<td><h:inputText id="subject" value="#{missionBean.subject}"
									required="true" requiredMessage="You must enter subject"
									a:placeholder="First Name"></h:inputText></td>
						</tr>
						<tr>
							<td><h:message for="subject" style="color:green" /></td>
						</tr>


						<tr>
							<td><h:outputText value="place"></h:outputText></td>
							<td><h:inputText id="place" value="#{missionBean.place}"
									required="true" requiredMessage="You must enter a Place"
									a:placeholder="City"></h:inputText></td>
						</tr>
						<tr>
							<td><h:message for="place" style="color:green" /></td>
						</tr>

						<tr>
							<td><h:outputText value="date debut"></h:outputText></td>
							<td><h:inputText id="datedeb"
									value="#{missionBean.datedebut}" required="true"
									requiredMessage="You must enter date">
									<f:convertDateTime pattern="yyyy/MM/dd" />
								</h:inputText></td>
						</tr>
						<tr>
							<td><h:message for="datedeb" style="color:green" /></td>
						</tr>

						<tr>
							<td><h:outputText value="date fin"></h:outputText></td>
							<td><h:inputText id="datefin" value="#{missionBean.datefin}"
									required="true" requiredMessage="You must enter date">
									<f:convertDateTime pattern="yyyy/MM/dd" />
								</h:inputText></td>
						</tr>
						<tr>
							<td><h:message for="datefin" style="color:green" /></td>
						</tr>


						<tr>
							<td><h:outputText value="description"></h:outputText></td>
							<td><h:inputTextarea id="description" required="true"
									value="#{missionBean.description}"
									requiredMessage="You must enter description"></h:inputTextarea></td>
						</tr>
						<tr>
							<td><h:message for="description" style="color:red" /></td>
						</tr>
						<tr>
							<td><h:outputText value="is accomondation provided"></h:outputText></td>
							<td><h:selectBooleanCheckbox
									value="#{missionBean.isProvidedAccd}"></h:selectBooleanCheckbox></td>
						</tr>
						<tr>
							<td><h:outputText value="is transport provided"></h:outputText></td>
							<td><h:selectBooleanCheckbox
									value="#{missionBean.isProvidedTrsp}"></h:selectBooleanCheckbox></td>
						</tr>
						<tr>
							<td><h:outputText value="first Skill"></h:outputText></td>
							<td><h:selectOneMenu id="slillvalue"
									value="#{missionBean.skill}" required="true"
									requiredMessage="You choose a skill ">
									<f:selectItem itemLabel="Choisir skill" itemValue="" />
									<f:selectItems value="#{skilll.skillTypes}" />
								</h:selectOneMenu></td>
						</tr>
						<tr>
							<td><h:outputText value="second Skill"></h:outputText></td>
							<td><h:selectOneMenu id="secondskill"
									value="#{missionBean.secondSkill}">
									<f:selectItem itemLabel="Choisir skill" itemValue="" />
									<f:selectItems value="#{skilll.skillTypes}" />
								</h:selectOneMenu></td>
						</tr>
						<tr>
							<td><h:outputText value="third Skill"></h:outputText></td>
							<td><h:selectOneMenu id="thirdskill"
									value="#{missionBean.thirdSkill}">
									<f:selectItem itemLabel="Choisir skill" itemValue="" />
									<f:selectItems value="#{skilll.skillTypes}" />
								</h:selectOneMenu></td>
						</tr>
						<tr>
							<td><h:message for="slillvalue" style="color:red" /></td>
						</tr>



						<tr>
							<td><h:outputText
									value="Estimation for the mission price in dinnars"></h:outputText></td>

							<td><h:inputText id="prix" value="#{missionBean.estimation}"
									disabled="#{Action.disabled}"
									a:placeholder="#{missionBean.estimation}">
								</h:inputText> <h:commandButton value="enable field" action="#{Action.able}"
									update="prix"></h:commandButton></td>
						</tr>

						<tr>
							<td colspan="2"><h:commandButton id="btn"
									value="Ajouter Mission" action="#{missionBean.addMission()}" />
								<h:message for="btn" /></td>
						</tr>
					</table>
				</h:form>
			</h:panelGroup>


			<tr>
				<td colspan="2"><h:commandButton value="Go Back"
						action="#{missionBean.goBack()}" /></td>
			</tr>
		</h:form>
	</ui:define>
</ui:composition>

PiDev-web/src/main/webapp/Pages/admin/gereremploye.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/tmp/template.xhtml">
	<ui:define name="title">Gerer les employes</ui:define>
	<ui:define name="content">

	
		</ui:define>
	
	
	
	
	
	</ui:composition>

PiDev-web/src/main/webapp/Pages/admin/missionList.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/tmp/layoutadmin1.xhtml"
	xmlns:a="http://xmlns.jcp.org/jsf/passthrough">

	<ui:define name="content">
		<h:form>
			<h:panelGroup columns="2" class="form-group">
				<h:form>
					<h:dataTable value="#{missionBean.missions}" var="mission"
						border="1">
						<h:column>
							<f:facet name="header">
								<h:outputText value="subject" />
							</f:facet>
							<h:outputText value="#{mission.subject}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="description" />
							</f:facet>
							<h:outputText value="#{mission.description}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="date ajout" />
							</f:facet>
							<h:outputText value="#{mission.date}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="skillsRequired 1" />
							</f:facet>
							<h:outputText value="#{mission.skillsRequired}" />
						</h:column>

						<h:column>
							<f:facet name="header">
								<h:outputText value="skillsRequired 2" />
							</f:facet>
							<h:outputText value="#{mission.secondSkill}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="skillsRequired 3" />
							</f:facet>
							<h:outputText value="#{mission.thirdSkill}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="date debut" />
							</f:facet>
							<h:outputText value="#{mission.datedebut}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="date fin" />
							</f:facet>
							<h:outputText value="#{mission.datefin}" />
						</h:column>


						<h:column>
							<f:facet name="header">
								<h:outputText value="Place" />
							</f:facet>
							<h:outputText value="#{mission.place}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="estimation" />
							</f:facet>
							<h:outputText value="#{mission.estimation}" />
						</h:column>



						<h:column>
							<f:facet name="header">
								<h:outputText value="isProvidedAccd" />
							</f:facet>
							<h:outputText
								value=" #{mission.isProvidedAccd == true ? 'Oui' : 'Non'}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="isProvidedTrsp" />
							</f:facet>
							<h:outputText
								value=" #{mission.isProvidedTrsp == true ? 'Oui' : 'Non'}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="etat" />
							</f:facet>
							<h:outputText value="#{mission.etat}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="nbr of participation" />
							</f:facet>
							<h:outputText value="#{mission.participantsNumber}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="Action" />
							</f:facet>
							<h:commandButton
								action="#{missionBean.deleteMission(mission.refrence)}"
								value="Delete" />
							<h:commandButton action="#{missionBean.displayDetails(mission)}"
								value="Display Details" />

						</h:column>

					</h:dataTable>
				</h:form>
			</h:panelGroup>
			<tr>
				<td colspan="2"><h:commandButton value="Go Back"
						action="#{missionBean.goBack()}" /></td>
			</tr>
			<h:form>
			</h:form>
		</h:form>
	</ui:define>
</ui:composition>

PiDev-web/src/main/webapp/Pages/admin/missionList2.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/tmp/layoutadmin1.xhtml"
	xmlns:a="http://xmlns.jcp.org/jsf/passthrough">
	<ui:define name="stylesheets">
		<link rel="stylesheets" href="#{request.contextPath}/resources/Back/css/plugins/footable/footable.core.css"></link>
	</ui:define>
	<ui:define name="javascripts">
		<script src="#{request.contextPath}/resources/Back/js/plugins/footable/footable.all.min.js"></script>
		<script>
		$(document).ready(function() {
            $('.footable').footable();
        });
		</script>
	</ui:define>
	<ui:define name="content">
		<div class="col-12">
			<div class="ibox">
				<div class="ibox-content">
					<table class="footable table table-stripped toggle-arrow-tiny"
						data-page-size="15">
						<thead>
							<tr>
							<th>subject</th>
								<th>description</th>
								<th data-hide="phone">date of add</th>
								<th data-hide="phone">skillsRequired</th>
								<th data-hide="phone">start date </th>
								<th data-hide="phone">end Date</th>
								<th data-hide="phone">Place</th>
								<th data-hide="phone">estimation</th>
								<th data-hide="phone">is Accomadtion Provided</th>
								<th data-hide="phone">is Trspport Provided</th>
								<th data-hide="phone">etat</th>
								<th data-hide="phone">nbr of participation</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
							<ui:repeat var="mission" value="#{missionBean.missions}">
								<tr>
									<td><h:outputText value="#{mission.subject}" /></td>
									<td><h:outputText value="#{mission.description}" /></td>
									<td><h:outputText value="#{mission.date}" /></td>
									<td>
										<h:outputText value="#{mission.skillsRequired} " />
										<h:outputText value="#{mission.secondSkill} " />
										<h:outputText value="#{mission.thirdSkill}" />	
									</td>
									<td><h:outputText value="#{mission.datedebut}" /></td>
									<td><h:outputText value="#{mission.datefin}" /></td>
									<td><h:outputText value="#{mission.place}" /></td>
									<td><h:outputText value="#{mission.estimation}" /></td>
									<td><h:outputText value="#{mission.isProvidedAccd == true ? 'Oui' : 'Non'}" /></td>
									<td><h:outputText value="#{mission.isProvidedTrsp == true ? 'Oui' : 'Non'}" /></td>
									<td><h:outputText value="#{mission.etat}" /></td>
									<td><h:outputText value="#{mission.participantsNumber}" /></td>
									<td>
										<h:form>
											<h:commandButton
												action="#{missionBean.deleteMission(mission.refrence)}"
												value="Delete" 
											/>
											<h:commandButton 
												action="#{missionBean.displayDetails(mission)}"
												value="Display Details" 
											/>
										</h:form>
									</td>
								</tr>
							</ui:repeat>
						</tbody>
						<tfoot>
							<tr>
								<td colspan="13">
									<ul class="pagination float-right"></ul>
								</td>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</ui:define>
</ui:composition>

PiDev-web/src/main/webapp/Pages/admin/welcomeManager.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
 <ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets" 
 template="/tmp/layoutadmin1.xhtml"
 xmlns:a="http://xmlns.jcp.org/jsf/passthrough"> 
<head>
    <style>
        #formdiv {
            margin: 0 auto;
        }
    </style>
</head>
 <ui:define name="content">
<h:body>
	 
<div id="formdiv">    
        <h:form id="frm">

 <ui:param name="page_name" value="Connexion" /> 
<h1>Welcome Manager</h1> 
<h:panelGroup columns="2"><h:form><table>
<tr><td colspan="2"> <h:commandButton value="Add Mission" action="#{missionBean.goToAddMission()}" /></td></tr>
<tr><td colspan="2"> <h:commandButton value="Display Missions" action="#{missionBean.goToDisplayMissions()}" /></td></tr>

</table></h:form></h:panelGroup>
 

</h:form>
</div>
</h:body>
</ui:define> 
</ui:composition>